name: Update Lease Programs and Inventory

on:
  push:
    paths:
      - 'new_lease_programs.pdf'
      - 'Inventory_Detail_20250527.xlsx'

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Java (required for tabula-py)
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jre

    - name: Convert PDF to Lease CSV
      run: python convert_pdf_to_csv.py

    - name: Update Inventory
      run: python ./update_inventory.py

    - name: Display CSV Outputs (for debug)
      run: |
        echo "------ Combined_Lease_Programs.csv ------"
        head -n 20 Combined_Lease_Programs.csv || echo "File not found"
        echo "------ Drivepath_Dealer_Inventory.csv ------"
        head -n 20 Drivepath_Dealer_Inventory.csv || echo "File not found"

    - name: Commit updated CSVs
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Combined_Lease_Programs.csv Drivepath_Dealer_Inventory.csv
        git commit -m "Update lease programs and inventory CSVs" || echo "No changes to commit"
        git push

    - name: Clean up raw uploads
      run: |
        rm -f new_lease_programs.pdf Inventory_Detail_20250527.xlsx
