name: Update Inventory CSV

on:
  push:
    paths:
      - 'Inventory_Detail_20250527.xlsx'
      - 'update_inventory.py'
      - '.github/workflows/update_data.yml'

jobs:
  update-inventory:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl

    - name: Run Inventory Update
      run: python update_inventory.py

    - name: Commit updated CSV
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Drivepath_Dealer_Inventory.csv
        git commit -m "Updated dealer inventory CSV" || echo "No changes to commit"
        git push
